import path from 'node:path';
import { linkOrCopyDir, rel, writeFile } from '../fs-utils.js';
import { convertClaudeAgentToCodex } from '../converters/claude-agent.js';
import type { BridgeOptions, BridgeReport, ClaudeWorkspace, PlannedOperation, TargetAdapter } from '../types.js';

export const codexAdapter: TargetAdapter = {
  name: 'codex',
  async plan(source: ClaudeWorkspace, options: BridgeOptions): Promise<PlannedOperation[]> {
    const operations: PlannedOperation[] = [];
    for (const skill of source.skills) {
      operations.push({ type: 'skill', action: options.mode, source: skill.dir, target: path.join(skill.projectRoot, '.agents', 'skills', skill.name) });
    }
    for (const agent of source.agents) {
      operations.push({ type: 'agent', action: 'convert', source: agent.file, target: path.join(agent.projectRoot, '.codex', 'agents', `${agent.name}.toml`) });
    }
    for (const setting of source.settings) {
      operations.push({ type: 'settings', action: 'diagnose', source: setting.file, target: path.join(source.root, 'AGENTS.md') });
    }
    if (source.workspaceGuide) {
      operations.push({ type: 'guide', action: 'generate', source: source.workspaceGuide.file, target: path.join(source.root, 'AGENTS.md') });
    }
    return operations;
  },
  async sync(source: ClaudeWorkspace, options: BridgeOptions, report: BridgeReport): Promise<void> {
    for (const skill of source.skills) {
      const target = path.join(skill.projectRoot, '.agents', 'skills', skill.name);
      const result = await linkOrCopyDir(skill.dir, target, options.mode, options.dryRun);
      report.add('codex', result === 'skipped' ? 'skipped skill already bridged' : `${options.mode} skill`, skill.dir, target);
    }
    for (const agent of source.agents) {
      const converted = await convertClaudeAgentToCodex(agent);
      const target = path.join(agent.projectRoot, '.codex', 'agents', converted.fileName);
      await writeFile(target, converted.content, options.dryRun);
      report.add('codex', 'converted agent', agent.file, target, converted.warnings);
    }
    if (source.workspaceGuide) {
      const settingsNote = source.settings.map((setting) => `- Claude setting detected: ${rel(source.root, setting.file)}`).join('\n');
      const content = `<!-- Generated by anyagent from ${rel(source.root, source.workspaceGuide.file)}. Edit the source, not this file. -->\n# Codex Workspace Guide (via anyagent)\n\nGenerated from ${rel(source.root, source.workspaceGuide.file)}.\n\n${settingsNote ? `## Claude Settings\n\n${settingsNote}\n\n` : ''}${source.workspaceGuide.content}`;
      const target = path.join(source.root, 'AGENTS.md');
      await writeFile(target, content, options.dryRun);
      report.add('codex', 'generated guide', source.workspaceGuide.file, target);
    }
  }
};
