import path from 'node:path';
import { rel, writeOutput } from '../fs-utils.js';
import { convertClaudeAgentToCursor, convertClaudeSkillToCursor } from '../converters/claude-agent.js';
import type { BridgeOptions, BridgeReport, ClaudeWorkspace, PlannedOperation, TargetAdapter } from '../types.js';

// Cursor discovers project context through `.cursor/rules/*.mdc` files. It has
// no native skill folder or subagent concept, so anyagent converts skills and
// agents into opt-in rules and emits an always-applied workspace rule from
// CLAUDE.md. Every conversion is reported as lossy where it genuinely is.
function rulesDir(projectRoot: string): string {
  return path.join(projectRoot, '.cursor', 'rules');
}

export const cursorAdapter: TargetAdapter = {
  name: 'cursor',
  async plan(source: ClaudeWorkspace): Promise<PlannedOperation[]> {
    const operations: PlannedOperation[] = [];
    for (const skill of source.skills) {
      operations.push({ type: 'skill', action: 'convert', source: skill.skillFile, target: path.join(rulesDir(skill.projectRoot), `skill-${skill.name}.mdc`) });
    }
    for (const agent of source.agents) {
      operations.push({ type: 'agent', action: 'convert', source: agent.file, target: path.join(rulesDir(agent.projectRoot), `agent-${agent.name}.mdc`) });
    }
    if (source.workspaceGuide) {
      operations.push({ type: 'guide', action: 'generate', source: source.workspaceGuide.file, target: path.join(rulesDir(source.root), 'workspace.mdc') });
    }
    return operations;
  },
  async sync(source: ClaudeWorkspace, options: BridgeOptions, report: BridgeReport): Promise<void> {
    for (const skill of source.skills) {
      const converted = await convertClaudeSkillToCursor(skill);
      const target = path.join(rulesDir(skill.projectRoot), converted.fileName);
      const result = await writeOutput(target, converted.content, options);
      report.add('cursor', 'converted skill', skill.skillFile, target, converted.warnings, result === 'changed');
    }
    for (const agent of source.agents) {
      const converted = await convertClaudeAgentToCursor(agent);
      const target = path.join(rulesDir(agent.projectRoot), converted.fileName);
      const result = await writeOutput(target, converted.content, options);
      report.add('cursor', 'converted agent', agent.file, target, converted.warnings, result === 'changed');
    }
    if (source.workspaceGuide) {
      const ref = rel(source.root, source.workspaceGuide.file);
      const content =
        `---\ndescription: "Workspace guidance (generated by anyagent from ${ref})"\nglobs:\nalwaysApply: true\n---\n` +
        `\n<!-- Generated by anyagent from ${ref}. Edit the source, not this file. -->\n` +
        `${source.workspaceGuide.content}`;
      const target = path.join(rulesDir(source.root), 'workspace.mdc');
      const result = await writeOutput(target, content, options);
      report.add('cursor', 'generated guide', source.workspaceGuide.file, target, [], result === 'changed');
    }
  }
};
