import path from 'node:path';
import { linkOrCopyDir, rel, writeOutput } from '../fs-utils.js';
import { convertClaudeAgentToHermes } from '../converters/claude-agent.js';
import type { BridgeOptions, BridgeReport, ClaudeWorkspace, PlannedOperation, TargetAdapter } from '../types.js';

export const hermesAdapter: TargetAdapter = {
  name: 'hermes',
  async plan(source: ClaudeWorkspace, options: BridgeOptions): Promise<PlannedOperation[]> {
    const operations: PlannedOperation[] = [];
    for (const skill of source.skills) {
      operations.push({ type: 'skill', action: options.mode, source: skill.dir, target: path.join(skill.projectRoot, '.hermes', 'skills', skill.name) });
    }
    for (const agent of source.agents) {
      operations.push({ type: 'agent', action: 'convert', source: agent.file, target: path.join(agent.projectRoot, '.hermes', 'agents', `${agent.name}.md`) });
    }
    if (source.workspaceGuide) {
      operations.push({ type: 'guide', action: 'generate', source: source.workspaceGuide.file, target: path.join(source.root, '.hermes', 'WORKSPACE.md') });
    }
    return operations;
  },
  async sync(source: ClaudeWorkspace, options: BridgeOptions, report: BridgeReport): Promise<void> {
    for (const skill of source.skills) {
      const target = path.join(skill.projectRoot, '.hermes', 'skills', skill.name);
      const result = await linkOrCopyDir(skill.dir, target, options.mode, options.dryRun || options.check);
      report.add('hermes', result === 'skipped' ? 'skipped skill already bridged' : `${options.mode} skill`, skill.dir, target, [], result === 'applied');
    }
    for (const agent of source.agents) {
      const converted = await convertClaudeAgentToHermes(agent);
      const target = path.join(agent.projectRoot, '.hermes', 'agents', converted.fileName);
      const result = await writeOutput(target, converted.content, options);
      report.add('hermes', 'converted agent', agent.file, target, converted.warnings, result === 'changed');
    }
    if (source.workspaceGuide) {
      const settingsBlock = source.settings.length > 0
        ? `\n\n## Claude Settings\n\n${source.settings.map((setting) => `- ${rel(source.root, setting.file)}`).join('\n')}`
        : '';
      const content = `<!-- Generated by anyagent from ${rel(source.root, source.workspaceGuide.file)}. Edit the source, not this file. -->\n# Hermes Workspace (via anyagent)\n\nGenerated from ${rel(source.root, source.workspaceGuide.file)}.${settingsBlock}\n\n${source.workspaceGuide.content}`;
      const target = path.join(source.root, '.hermes', 'WORKSPACE.md');
      const result = await writeOutput(target, content, options);
      report.add('hermes', 'generated guide', source.workspaceGuide.file, target, [], result === 'changed');
    }
  }
};
