import path from 'node:path';
import { rel, writeOutput } from '../fs-utils.js';
import { convertClaudeAgentToWindsurf, convertClaudeSkillToWindsurf } from '../converters/claude-agent.js';
import type { BridgeOptions, BridgeReport, ClaudeWorkspace, PlannedOperation, TargetAdapter } from '../types.js';

// Windsurf discovers project context through `.windsurf/rules/*.md` (with a
// `trigger` activation mode) and reusable procedures through
// `.windsurf/workflows/*.md`. anyagent maps skills → workflows (the closest
// native concept), agents → manually-triggered rules, and CLAUDE.md → an
// always-on workspace rule. No skill folder, no subagent — lossy spots reported.
function rulesDir(projectRoot: string): string {
  return path.join(projectRoot, '.windsurf', 'rules');
}

function workflowsDir(projectRoot: string): string {
  return path.join(projectRoot, '.windsurf', 'workflows');
}

export const windsurfAdapter: TargetAdapter = {
  name: 'windsurf',
  async plan(source: ClaudeWorkspace): Promise<PlannedOperation[]> {
    const operations: PlannedOperation[] = [];
    for (const skill of source.skills) {
      operations.push({ type: 'skill', action: 'convert', source: skill.skillFile, target: path.join(workflowsDir(skill.projectRoot), `${skill.name}.md`) });
    }
    for (const agent of source.agents) {
      operations.push({ type: 'agent', action: 'convert', source: agent.file, target: path.join(rulesDir(agent.projectRoot), `agent-${agent.name}.md`) });
    }
    if (source.workspaceGuide) {
      operations.push({ type: 'guide', action: 'generate', source: source.workspaceGuide.file, target: path.join(rulesDir(source.root), 'workspace.md') });
    }
    return operations;
  },
  async sync(source: ClaudeWorkspace, options: BridgeOptions, report: BridgeReport): Promise<void> {
    for (const skill of source.skills) {
      const converted = await convertClaudeSkillToWindsurf(skill);
      const target = path.join(workflowsDir(skill.projectRoot), converted.fileName);
      const result = await writeOutput(target, converted.content, options);
      report.add('windsurf', 'converted skill', skill.skillFile, target, converted.warnings, result === 'changed');
    }
    for (const agent of source.agents) {
      const converted = await convertClaudeAgentToWindsurf(agent);
      const target = path.join(rulesDir(agent.projectRoot), converted.fileName);
      const result = await writeOutput(target, converted.content, options);
      report.add('windsurf', 'converted agent', agent.file, target, converted.warnings, result === 'changed');
    }
    if (source.workspaceGuide) {
      const ref = rel(source.root, source.workspaceGuide.file);
      const content =
        `---\ntrigger: always_on\ndescription: "Workspace guidance (generated by anyagent from ${ref})"\n---\n` +
        `\n<!-- Generated by anyagent from ${ref}. Edit the source, not this file. -->\n` +
        `${source.workspaceGuide.content}`;
      const target = path.join(rulesDir(source.root), 'workspace.md');
      const result = await writeOutput(target, content, options);
      report.add('windsurf', 'generated guide', source.workspaceGuide.file, target, [], result === 'changed');
    }
  }
};
